[project]
name = "physics7516-ml-final-project"
version = "0.1.0"
description = "Final project of the 2026 Summer Term Lecture 'physics7516: Machine Learning for Quantum Scientists' at the University of Bonn"
authors = [
    { name = "Leon Galbas", email = "contact@leon-galbas.de" }
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "h5py>=3.16.0",
    "ipympl>=0.10.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.0",
    "numpy>=2.5.1",
    "pandas>=3.0.3",
    "pyqt5>=5.15.11",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.0",
    "torch>=2.13.0",
    "tqdm>=4.68.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]
